---
- hosts: all
  vars:
    - dest_user: "{{ lookup('env','NB_USER') | default('hallgato', true) }}"
    - dest_uid: "{{ lookup('env','NB_UID') | default(10000, true) }}"
  roles:
    - role: docker
      tags: update
  tasks:
    - name: install required packages
      apt:
        pkg:
          - lubuntu-desktop
          - language-pack-hu
          - language-pack-gnome-hu
          - firefox-locale-hu
          - hunspell-hu
          - aspell-hu
          - gnome-user-docs-hu
          - apt-transport-https
          - python3-pip
          - locales
          - git
          - sudo
          - mc
      tags: update
    - name: upgrade distribution packages
      apt:
        upgrade: full
      tags: update
    - name: install required pip packages
      pip:
        executable: pip3
        name:
          - pipenv
          - "docker-compose==1.25.4"
      tags: update
    - name: setup system locale
      command:
        cmd: "{{ item }}"
      with_items:
        - "locale-gen hu_HU.UTF-8"
        - "update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8"
      tags: update
    - name: "add default user {{ dest_user }}:{{ dest_uid }}"
      user:
        name: "{{ dest_user }}"
        home: "/home/{{ dest_user }}"
        comment: Hallgato
        password: $6$7uQS525NCE04TAQA$FS4oHPvK6j32ylaB9mN7ftpfDeKus0OhUGvq9GkxbLaFs/OYcgWmEr1oMOxprLhZUqxf0PAKQSinKfbdQ0INv0
        groups: sudo, docker
        shell: /bin/bash
        uid: "{{ dest_uid }}"
    - name: checkout oe-itseclabs jupyter git repo
      git:
        repo: https://github.com/mcree/oe-itseclabs-jupyter.git
        dest: "/home/{{ dest_user }}/oe-itseclabs"
        force: no
        update: yes
      register: git_result
      tags: update
    - name: build docker image for jupyter
      docker_image:
        name: jupyter
        source: build
        force_source: yes
        build:
          path: "/home/{{ dest_user }}/oe-itseclabs"
      when: git_result.before != git_result.after
      tags: update
    - name: fix /home permissions
      file:
          path: "/home/{{ dest_user }}"
          recurse: yes
          owner: "{{ dest_user }}"
      tags: update
    - name: copy files to /home
      copy:
        src: files/home/
        dest: "/home/{{ dest_user }}/"
        owner: "{{ dest_user }}"
      tags: update
    - name: copy files to /etc
      copy:
        src: files/etc/
        dest: /etc/
        owner: root
      tags: update
    - name: copy files to /usr
      copy:
        src: files/usr/
        dest: /usr/
        owner: root
        mode: preserve
      tags: update
    - name: update CA certs
      command: update-ca-certificates
      tags: update
    - name: clean up environment
      command:
        cmd: "{{ item }}"
      with_items:
        - "apt-get autoremove -f -y"
        - "apt-get clean"
      tags: update
