---
- hosts: all
  tasks:
    - name: update the updater script
      copy:
        src: ../files/usr/
        dest: /usr/
        owner: root
        mode: preserve
      tags: update
    - name: print debug message
      fail:
        msg: "!!! PLEASE RERUN THE UPDATE !!!"
