version: '3.1'

services:

  server:
    build: ./server
    image: sshd
    hostname: ssh-server
    volumes:
      - "./server/ssh:/etc/ssh"

  client:
    build: ./client
    image: sshclient
    hostname: ssh-client
    stdin_open: true
    tty: true
    links: 
      - server
    volumes:
      - "./client_tmux:/tmux-sock"
