// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1581521321);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1420);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1581521291);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{40e884cb-a9ac-48d6-978d-d97da63f7c21}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1581521345214");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1581523123214");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1581521296038");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1581524896038");
user_pref("browser.search.region", "HU");
user_pref("browser.slowStartup.averageTime", 2485);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200117190643");
user_pref("browser.startup.homepage_override.mstone", "72.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1581521293);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1581521294612");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "3bfd833615bc4da982c0af937639279a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.2");
user_pref("extensions.lastPlatformVersion", "72.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e41d4de0-bdf8-43b6-b409-e330384cda30\",\"formautofill@mozilla.org\":\"d592c086-8361-4845-a4b9-a8125fb1187a\",\"screenshots@mozilla.org\":\"17a84228-c554-4069-aef6-42eadd712d87\",\"webcompat-reporter@mozilla.org\":\"a4c5003c-16e2-4960-8682-a8a95d8b29c0\",\"webcompat@mozilla.org\":\"f17e6aed-eed2-4764-9dda-e81f838a2688\",\"default-theme@mozilla.org\":\"fed22150-32ff-4ab5-93e8-e8bee2578d07\",\"google@search.mozilla.org\":\"e221e6b6-5955-4458-b0ef-495bc4e6d8fc\",\"ddg@search.mozilla.org\":\"28049e0f-0db3-4f66-a75c-74efef5cf43f\",\"vatera@search.mozilla.org\":\"1ebf2220-af7c-40fb-a5db-b5cd5383e946\",\"wikipedia@search.mozilla.org\":\"3bdc9fb5-5fe7-478d-8221-00ab11b0a0e1\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 59068);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.disable_button.openCertManager", false);
user_pref("security.sandbox.content.tempDirSuffix", "f845c445-ec26-4095-8bcb-d22ada147379");
user_pref("security.sandbox.plugin.tempDirSuffix", "16869186-a93a-4448-aa11-fb8b0ee91d0f");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1581521290);
user_pref("toolkit.telemetry.cachedClientID", "c49f6d2f-82a3-459e-8e10-4f85522f5f02");
user_pref("toolkit.telemetry.previousBuildID", "20200117190643");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
